version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - v2-{{ checksum "openid-connect.cabal" }}-{{ checksum "stack.yaml" }}
            - v2- # used if checksum fail
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack --no-terminal test
      - save_cache:
          name: Cache Dependencies
          key: v2-{{ checksum "openid-connect.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
